title: "Learn To Be Blog"
author: "Neeraj"
url: "https://learntobefoundation.github.io"   # GitHub Pages URL
baseurl: ""                         # empty for organization main pages site

theme: pandoc-markdown-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-pandoc                  # lets Jekyll call Pandoc

markdown: Pandoc
pandoc:
  extensions:
    - from: 'markdown+smart+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'
    - template: '_template'
    - katex                         # KaTeX for math
    - toc                           # auto table-of-contents
    - M: 'site__baseurl=/'          # duplicate of baseurl per theme docs
permalink: /blog/:title/