title: "Neeraj’s Blog"
author: "Neeraj"
url: "https://learntobefoundation.github.io"   # GitHub Pages URL
baseurl: "/ltb-blog"                # repository name for GitHub Pages

theme: pandoc-markdown-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-pandoc                  # lets Jekyll call Pandoc

markdown: Pandoc
pandoc:
  extensions:
    - from: 'markdown+smart+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'
    - template: '_template'
    - katex                         # KaTeX for math
    - toc                           # auto table-of-contents
    - M: 'site__baseurl=/ltb-blog'  # duplicate of baseurl per theme docs
permalink: /:year/:month/:day/:title/