title: "Learn To Be Blog"
author: "Neeraj"
url: "https://learntobefoundation.github.io/learn-to-be.github.io"   # Full GitHub Pages URL
baseurl: "/blog"  # Just the blog subdirectory

theme: pandoc-markdown-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-pandoc                  # lets Jekyll call Pandoc

markdown: Pandoc
pandoc:
  extensions:
    - from: 'markdown+smart+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'
    - template: '_template'
    - katex                         # KaTeX for math
    - toc                           # auto table-of-contents
    - M: 'site__baseurl=/blog'  # duplicate of baseurl per theme docs
permalink: /:title/

