name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.11'

      - name: Install pandoc-sidenote
        run: |
          # Download pre-built pandoc-sidenote binary
          wget -O /tmp/pandoc-sidenote https://github.com/jez/pandoc-sidenote/releases/download/0.23.0.0/pandoc-sidenote-0.23.0.0-linux-x86_64
          chmod +x /tmp/pandoc-sidenote
          sudo mv /tmp/pandoc-sidenote /usr/local/bin/pandoc-sidenote

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --baseurl "/blog"
        env:
          JEKYLL_ENV: production

      - name: Copy all assets to blog directory
        run: |
          # Create the blog/assets directory if it doesn't exist
          mkdir -p _site/blog/assets
          
          # Copy all assets recursively while preserving directory structure
          cp -r _site/assets/* _site/blog/assets/
          
      - name: Print output directory structure
        run: |
          echo "Generated _site directory structure:"
          find _site -type f | sort

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
